_target_: src.models.t5_module.T5LitModule

# Perplexity metric configuration
ignore_index: -100  # Standard T5 label ignore index

# single model config used by LitModule
t5_model:
  _target_: src.models.components.t5_model.T5Model
  pretrained_model_name_or_path: t5-base
  enable_gradient_checkpointing: true

# optimizer settings
optimizer:
  _target_: torch.optim.AdamW
  lr: 5e-4
  betas: [0.9, 0.95]
  weight_decay: 0.01
  _partial_: true

scheduler: null 